BASE_URL = "https://www.saucedemo.com/"
username_id = "user-name"
password_id = "password"
login_button_id = "login-button"
userNameErrorMessage_xpath = "//*[@id='login_button_container']/div/form/div[3]/h3"
userNameErrorMessage_text = "Epic sadface: Username is required"
passwordErrorMessage_xpath = "//*[@id='login_button_container']/div/form/div[3]/h3"
lockedErrorMessage_xpath = "//*[@id='login_button_container']/div/form/div[3]/h3"
lockedErrorMessage_text = "Epic sadface: Sorry, this user has been locked out."
productsClassName_text = "inventory_item_description"